### PR TITLE
Skip N starting values for LineSet and LineChart

### PR DESCRIPTION
**Pull request by AndroidGecko**
Ability to skip N values from particular lineSet

example
    String[] x1 = new String[] { "", "10", "20", "30", "40", "50", "60" };
    float[] y1 = new float[] { 100, 60, 35, 20, 12, 8, 5 };

    String[] x2 = new String[] { "", "10", "20", "30", "40", "50", "60" };
    float[] y2 = new float[] { 100, 100, 60, 40, 20, 15, 12 };

then I do 

dataSet.setSkipStartingPoints(1);

on LineSet which has x2,y2

this is the result 

screenshot_2015-01-09-13-04-43

### CODE REVIEW

**Comment by diogobernardino** [comment]
That can indeed be useful, I will review it carefully later and merge it. Thanks!

**Comment by AndroidGecko** [comment]
also, same thing could happen with dataSet.setSkipEndingPoints(1); 
then you could mix a lot of smaller pieces to produce one mixed graph (a bit of dashed, a bit of solid etc)

**Comment by diogobernardino** [comment]
Merged! Yes, definitely a nice-to-have. I think I will only set the methods names to ```dataSet.beginAt(index)``` and ```dataSet.endAt(index)```.

**Comment by diogobernardino** [comment]
In case you would like to check, I've changed a bit the way it was implemented, added the ```dataSet.endAt(index)```method and push it to dev branch already.

**Comment by AndroidGecko** [comment]
Great! Thanks Diogo, yes much sane naming.. going to use this now

**Pull request merged**
